server:
  port: 8080

spring:
  application:
    name: traditional-market
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${DB_ID}
    password: ${DB_PW}

  redis:
    host: localhost
    port: 6379

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KET}
    region:
      static: ${STATIC}
    s3:
      bucket: ${BUCKET}

jwt:
  issuer: songwc3@gmail.com
  a_secret_key: ${A_KEY}
  r_secret_key: ${R_KEY}
